//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025/6/5 下午 02:31:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Api.Entities
{
    /// <summary>
    /// 使用者登入帳號
    /// </summary>
    public partial class Account {

        public Account()
        {
            this.Status = 100;
            this.IsSuper = false;
            this.IsDeleted = false;
            this.TryCount = 0;
            OnCreated();
        }

        /// <summary>
        /// 帳號(員工代碼)
        /// </summary>
        [Key]
        [StringLength(30)]
        [Required()]
        public string No { get; set; }

        /// <summary>
        /// 姓名
        /// </summary>
        [StringLength(30)]
        public string Name { get; set; }

        /// <summary>
        /// 聯絡電話
        /// </summary>
        [StringLength(30)]
        public string Phone { get; set; }

        /// <summary>
        /// 電子郵件
        /// </summary>
        [StringLength(100)]
        public string Email { get; set; }

        /// <summary>
        /// 使用者密碼
        /// </summary>
        [StringLength(64)]
        public string HashPermit { get; set; }

        /// <summary>
        /// 帳號有效日期
        /// </summary>
        public DateTime? Expiration { get; set; }

        /// <summary>
        /// 帳號狀態
        /// </summary>
        [Required()]
        public int Status { get; set; }

        /// <summary>
        /// 建立時間
        /// </summary>
        [Required()]
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// 最後登入時間
        /// </summary>
        public DateTime? LastLoginTime { get; set; }

        /// <summary>
        /// 修改時間
        /// </summary>
        public DateTime? UpdateTime { get; set; }

        /// <summary>
        /// 是否為超級使用者
        /// </summary>
        [Required()]
        public bool IsSuper { get; set; }

        /// <summary>
        /// 註記刪除
        /// </summary>
        [Required()]
        public bool IsDeleted { get; set; }

        /// <summary>
        /// 密碼變更時間
        /// </summary>
        public DateTime? PermitChangeTime { get; set; }

        /// <summary>
        /// 密碼錯誤次數
        /// </summary>
        [Required()]
        public int TryCount { get; set; }

        /// <summary>
        /// 帳號配置文件
        /// </summary>
        [StringLength(20)]
        public string Profile { get; set; }

        /// <summary>
        /// 身分證號
        /// </summary>
        [StringLength(30)]
        public string Identifier { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
