//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025/6/5 下午 02:31:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Api.Entities
{
    /// <summary>
    /// 稽核事件
    /// </summary>
    public partial class AuditEvent {

        public AuditEvent()
        {
            OnCreated();
        }

        /// <summary>
        /// 代碼ID
        /// </summary>
        [Key]
        [Required()]
        public int Id { get; set; }

        /// <summary>
        /// 建立時間
        /// </summary>
        [Required()]
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// 資料類別
        /// </summary>
        [StringLength(100)]
        public string DataType { get; set; }

        /// <summary>
        /// 資料 pKey
        /// </summary>
        [StringLength(50)]
        public string DataKey { get; set; }

        /// <summary>
        /// 資料內容
        /// </summary>
        public string Data { get; set; }

        /// <summary>
        /// 使用者帳號
        /// </summary>
        [StringLength(30)]
        public string AccountNo { get; set; }

        /// <summary>
        /// 用戶端IP
        /// </summary>
        [StringLength(50)]
        public string HostAddress { get; set; }

        /// <summary>
        /// 執行動作
        /// </summary>
        [StringLength(500)]
        public string ProcessStack { get; set; }

        /// <summary>
        /// 記錄類型
        /// </summary>
        public int? Type { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
