//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025/6/5 下午 02:31:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.Configuration;
using MySql.EntityFrameworkCore.Extensions;

namespace Api.Entities
{

    public partial class Db : DbContext
    {

        public Db() :
            base()
        {
            OnCreated();
        }

        public Db(DbContextOptions<Db> options) :
            base(options)
        {
            OnCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured ||
                (!optionsBuilder.Options.Extensions.OfType<RelationalOptionsExtension>().Any(ext => !string.IsNullOrEmpty(ext.ConnectionString) || ext.Connection != null) &&
                 !optionsBuilder.Options.Extensions.Any(ext => !(ext is RelationalOptionsExtension) && !(ext is CoreOptionsExtension))))
            {
                optionsBuilder.UseMySQL(GetConnectionString("DB"));
                optionsBuilder.UseLazyLoadingProxies();
            }
            CustomizeConfiguration(ref optionsBuilder);
            base.OnConfiguring(optionsBuilder);
        }

        private static string GetConnectionString(string connectionStringName)
        {
            var configurationBuilder = new ConfigurationBuilder().AddJsonFile("appsettings.json", optional: true, reloadOnChange: false);
            var configuration = configurationBuilder.Build();
            return configuration.GetConnectionString(connectionStringName);
        }

        partial void CustomizeConfiguration(ref DbContextOptionsBuilder optionsBuilder);

        public virtual DbSet<ExamData> ExamDatas
        {
            get;
            set;
        }

        public virtual DbSet<ImgPara> ImgParas
        {
            get;
            set;
        }

        public virtual DbSet<ImportLog> ImportLogs
        {
            get;
            set;
        }

        public virtual DbSet<PatientDetail> PatientDetails
        {
            get;
            set;
        }

        public virtual DbSet<PatientMain> PatientMains
        {
            get;
            set;
        }

        public virtual DbSet<ReportCodeDesc> ReportCodeDescs
        {
            get;
            set;
        }

        public virtual DbSet<ReportSpecialWord> ReportSpecialWords
        {
            get;
            set;
        }

        public virtual DbSet<Account> Accounts
        {
            get;
            set;
        }

        public virtual DbSet<AuditEvent> AuditEvents
        {
            get;
            set;
        }

        public virtual DbSet<Systemcode> Systemcodes
        {
            get;
            set;
        }

        public virtual DbSet<Pwdchangelog> Pwdchangelogs
        {
            get;
            set;
        }

        public virtual DbSet<UserProfile> UserProfiles
        {
            get;
            set;
        }

        public virtual DbSet<DicomPicture> DicomPictures
        {
            get;
            set;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            this.ExamDataMapping(modelBuilder);
            this.CustomizeExamDataMapping(modelBuilder);

            this.ImgParaMapping(modelBuilder);
            this.CustomizeImgParaMapping(modelBuilder);

            this.ImportLogMapping(modelBuilder);
            this.CustomizeImportLogMapping(modelBuilder);

            this.PatientDetailMapping(modelBuilder);
            this.CustomizePatientDetailMapping(modelBuilder);

            this.PatientMainMapping(modelBuilder);
            this.CustomizePatientMainMapping(modelBuilder);

            this.ReportCodeDescMapping(modelBuilder);
            this.CustomizeReportCodeDescMapping(modelBuilder);

            this.ReportSpecialWordMapping(modelBuilder);
            this.CustomizeReportSpecialWordMapping(modelBuilder);

            this.AccountMapping(modelBuilder);
            this.CustomizeAccountMapping(modelBuilder);

            this.AuditEventMapping(modelBuilder);
            this.CustomizeAuditEventMapping(modelBuilder);

            this.SystemcodeMapping(modelBuilder);
            this.CustomizeSystemcodeMapping(modelBuilder);

            this.PwdchangelogMapping(modelBuilder);
            this.CustomizePwdchangelogMapping(modelBuilder);

            this.UserProfileMapping(modelBuilder);
            this.CustomizeUserProfileMapping(modelBuilder);

            this.DicomPictureMapping(modelBuilder);
            this.CustomizeDicomPictureMapping(modelBuilder);

            RelationshipsMapping(modelBuilder);
            CustomizeMapping(ref modelBuilder);
        }

        #region ExamData Mapping

        private void ExamDataMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ExamData>().ToTable(@"exam_data", @"pacs");
            modelBuilder.Entity<ExamData>().Property(x => x.ExamDataNo).HasColumnName(@"ExamDataNo").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(14, 0);
            modelBuilder.Entity<ExamData>().Property(x => x.StudyID).HasColumnName(@"StudyID").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(15).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<ExamData>().Property(x => x.ExamDateTime).HasColumnName(@"ExamDateTime").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<ExamData>().Property(x => x.Memo1).HasColumnName(@"memo1").HasColumnType(@"text").ValueGeneratedOnAdd().HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<ExamData>().Property(x => x.AdditionalPatientHistory).HasColumnName(@"AdditionalPatientHistory").HasColumnType(@"text").ValueGeneratedOnAdd().HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<ExamData>().Property(x => x.English).HasColumnName(@"english").HasColumnType(@"text").ValueGeneratedOnAdd().HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<ExamData>().Property(x => x.Recommand).HasColumnName(@"recommand").HasColumnType(@"text").ValueGeneratedOnAdd().HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<ExamData>().HasKey(@"ExamDataNo");
        }

        partial void CustomizeExamDataMapping(ModelBuilder modelBuilder);

        #endregion

        #region ImgPara Mapping

        private void ImgParaMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ImgPara>().ToTable(@"img_para", @"pacs");
            modelBuilder.Entity<ImgPara>().Property(x => x.Pid).HasColumnName(@"pid").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(3, 0);
            modelBuilder.Entity<ImgPara>().Property(x => x.ImgPosition).HasColumnName(@"img_position").HasColumnType(@"int").ValueGeneratedOnAdd().HasPrecision(10, 0).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<ImgPara>().Property(x => x.ImgWidth).HasColumnName(@"img_width").HasColumnType(@"int").ValueGeneratedOnAdd().HasPrecision(10, 0).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<ImgPara>().Property(x => x.ImgHeight).HasColumnName(@"img_height").HasColumnType(@"int").ValueGeneratedOnAdd().HasPrecision(10, 0).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<ImgPara>().Property(x => x.ImgRota).HasColumnName(@"img_rota").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0).HasDefaultValueSql(@"0");
            modelBuilder.Entity<ImgPara>().Property(x => x.ImgCount).HasColumnName(@"img_count").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0).HasDefaultValueSql(@"4");
            modelBuilder.Entity<ImgPara>().HasKey(@"Pid");
            modelBuilder.Entity<ImgPara>().HasIndex(@"Pid").IsUnique(true);
        }

        partial void CustomizeImgParaMapping(ModelBuilder modelBuilder);

        #endregion

        #region ImportLog Mapping

        private void ImportLogMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ImportLog>().ToTable(@"import_log", @"pacs");
            modelBuilder.Entity<ImportLog>().Property(x => x.Iid).HasColumnName(@"iid").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<ImportLog>().Property(x => x.Sname).HasColumnName(@"sname").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(60).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<ImportLog>().Property(x => x.Fname).HasColumnName(@"fname").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(60).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<ImportLog>().Property(x => x.Bname).HasColumnName(@"bname").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(80).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<ImportLog>().Property(x => x.Idatetime).HasColumnName(@"idatetime").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<ImportLog>().Property(x => x.Odatetime).HasColumnName(@"odatetime").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<ImportLog>().Property(x => x.Sdatetime).HasColumnName(@"sdatetime").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<ImportLog>().Property(x => x.Status).HasColumnName(@"status").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(1).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<ImportLog>().HasKey(@"Iid");
            modelBuilder.Entity<ImportLog>().HasIndex(@"Iid").IsUnique(true);
        }

        partial void CustomizeImportLogMapping(ModelBuilder modelBuilder);

        #endregion

        #region PatientDetail Mapping

        private void PatientDetailMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<PatientDetail>().ToTable(@"patient_detail", @"pacs");
            modelBuilder.Entity<PatientDetail>().Property(x => x.DetailNo).HasColumnName(@"DetailNo").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(14, 0);
            modelBuilder.Entity<PatientDetail>().Property(x => x.StudyID).HasColumnName(@"StudyID").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(15);
            modelBuilder.Entity<PatientDetail>().Property(x => x.PatientID).HasColumnName(@"PatientID").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<PatientDetail>().Property(x => x.SeriesNumber).HasColumnName(@"SeriesNumber").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(3, 0).HasDefaultValueSql(@"0");
            modelBuilder.Entity<PatientDetail>().Property(x => x.StudyDate).HasColumnName(@"StudyDate").HasColumnType(@"date").ValueGeneratedOnAdd().HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<PatientDetail>().Property(x => x.ContentDate).HasColumnName(@"ContentDate").HasColumnType(@"date").ValueGeneratedOnAdd().HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<PatientDetail>().Property(x => x.StudyTime).HasColumnName(@"StudyTime").HasColumnType(@"time").ValueGeneratedOnAdd().HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<PatientDetail>().Property(x => x.ContentTime).HasColumnName(@"ContentTime").HasColumnType(@"time").ValueGeneratedOnAdd().HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<PatientDetail>().Property(x => x.Modality).HasColumnName(@"Modality").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(10).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<PatientDetail>().Property(x => x.OperatorName).HasColumnName(@"OperatorName").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(20).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<PatientDetail>().Property(x => x.Manufacturer).HasColumnName(@"Manufacturer").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(50).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<PatientDetail>().Property(x => x.BodyPartExamined).HasColumnName(@"BodyPartExamined").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(100).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<PatientDetail>().Property(x => x.ProtocolName).HasColumnName(@"ProtocolName").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(50).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<PatientDetail>().Property(x => x.AccessionNumber).HasColumnName(@"AccessionNumber").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(30).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<PatientDetail>().Property(x => x.InstanceNumber).HasColumnName(@"InstanceNumber").HasColumnType(@"tinyint").ValueGeneratedOnAdd().HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<PatientDetail>().Property(x => x.Image).HasColumnName(@"image").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(50).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<PatientDetail>().Property(x => x.Status).HasColumnName(@"Status").HasColumnType(@"char").IsRequired().ValueGeneratedNever().HasMaxLength(1).HasDefaultValueSql(@"'N'");
            modelBuilder.Entity<PatientDetail>().Property(x => x.AdditionalPatientHistory).HasColumnName(@"AdditionalPatientHistory").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(100).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<PatientDetail>().HasKey(@"DetailNo");
        }

        partial void CustomizePatientDetailMapping(ModelBuilder modelBuilder);

        #endregion

        #region PatientMain Mapping

        private void PatientMainMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<PatientMain>().ToTable(@"patient_main", @"pacs");
            modelBuilder.Entity<PatientMain>().Property(x => x.PatientMainNo).HasColumnName(@"PatientMainNo").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(9, 0);
            modelBuilder.Entity<PatientMain>().Property(x => x.PatientID).HasColumnName(@"PatientID").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<PatientMain>().Property(x => x.PatientName).HasColumnName(@"PatientName").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<PatientMain>().Property(x => x.PatientBirthDate).HasColumnName(@"PatientBirthDate").HasColumnType(@"date").ValueGeneratedOnAdd().HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<PatientMain>().Property(x => x.PatientSex).HasColumnName(@"PatientSex").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<PatientMain>().Property(x => x.OtherPatientID).HasColumnName(@"OtherPatientID").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(10).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<PatientMain>().HasKey(@"PatientMainNo");
        }

        partial void CustomizePatientMainMapping(ModelBuilder modelBuilder);

        #endregion

        #region ReportCodeDesc Mapping

        private void ReportCodeDescMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ReportCodeDesc>().ToTable(@"report_code_desc", @"pacs");
            modelBuilder.Entity<ReportCodeDesc>().Property(x => x.ReportCodeDescNo).HasColumnName(@"ReportCodeDescNo").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(8, 0);
            modelBuilder.Entity<ReportCodeDesc>().Property(x => x.ReportCode).HasColumnName(@"ReportCode").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            modelBuilder.Entity<ReportCodeDesc>().Property(x => x.ReportDesc).HasColumnName(@"ReportDesc").HasColumnType(@"text").ValueGeneratedOnAdd().HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<ReportCodeDesc>().Property(x => x.UserID).HasColumnName(@"UserID").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<ReportCodeDesc>().HasKey(@"ReportCodeDescNo");
        }

        partial void CustomizeReportCodeDescMapping(ModelBuilder modelBuilder);

        #endregion

        #region ReportSpecialWord Mapping

        private void ReportSpecialWordMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ReportSpecialWord>().ToTable(@"report_special_word", @"pacs");
            modelBuilder.Entity<ReportSpecialWord>().Property(x => x.ReportSpecialWordNo).HasColumnName(@"ReportSpecialWordNo").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(8, 0);
            modelBuilder.Entity<ReportSpecialWord>().Property(x => x.ReportSpecialCode).HasColumnName(@"ReportSpecialCode").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(10).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<ReportSpecialWord>().Property(x => x.ReportSpecialGrade).HasColumnName(@"ReportSpecialGrade").HasColumnType(@"int").ValueGeneratedOnAdd().HasPrecision(1, 0).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<ReportSpecialWord>().Property(x => x.ReportSpecialWord1).HasColumnName(@"ReportSpecialWord").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(255).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<ReportSpecialWord>().Property(x => x.UserID).HasColumnName(@"UserID").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(255).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<ReportSpecialWord>().HasKey(@"ReportSpecialWordNo");
        }

        partial void CustomizeReportSpecialWordMapping(ModelBuilder modelBuilder);

        #endregion

        #region Account Mapping

        private void AccountMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Account>().ToTable(@"account", @"pacs");
            modelBuilder.Entity<Account>().Property(x => x.No).HasColumnName(@"no").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(30);
            modelBuilder.Entity<Account>().Property(x => x.Name).HasColumnName(@"name").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(30).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<Account>().Property(x => x.Phone).HasColumnName(@"phone").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(30).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<Account>().Property(x => x.Email).HasColumnName(@"email").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(100).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<Account>().Property(x => x.HashPermit).HasColumnName(@"hash_permit").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(64).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<Account>().Property(x => x.Expiration).HasColumnName(@"expiration").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<Account>().Property(x => x.Status).HasColumnName(@"status").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0).HasDefaultValueSql(@"100");
            modelBuilder.Entity<Account>().Property(x => x.CreateTime).HasColumnName(@"create_time").HasColumnType(@"datetime").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"current_timestamp()");
            modelBuilder.Entity<Account>().Property(x => x.LastLoginTime).HasColumnName(@"last_login_time").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<Account>().Property(x => x.UpdateTime).HasColumnName(@"update_time").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<Account>().Property(x => x.IsSuper).HasColumnName(@"is_super").HasColumnType(@"bit").IsRequired().ValueGeneratedNever().HasPrecision(1).HasDefaultValueSql(@"b'0'");
            modelBuilder.Entity<Account>().Property(x => x.IsDeleted).HasColumnName(@"is_deleted").HasColumnType(@"bit").IsRequired().ValueGeneratedNever().HasPrecision(1).HasDefaultValueSql(@"b'0'");
            modelBuilder.Entity<Account>().Property(x => x.PermitChangeTime).HasColumnName(@"permit_change_time").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<Account>().Property(x => x.TryCount).HasColumnName(@"try_count").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever().HasPrecision(5, 0).HasDefaultValueSql(@"0");
            modelBuilder.Entity<Account>().Property(x => x.Profile).HasColumnName(@"profile").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(20).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<Account>().Property(x => x.Identifier).HasColumnName(@"Identifier").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(30).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<Account>().HasKey(@"No");
        }

        partial void CustomizeAccountMapping(ModelBuilder modelBuilder);

        #endregion

        #region AuditEvent Mapping

        private void AuditEventMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AuditEvent>().ToTable(@"audit_event", @"pacs");
            modelBuilder.Entity<AuditEvent>().Property(x => x.Id).HasColumnName(@"Id").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(11, 0);
            modelBuilder.Entity<AuditEvent>().Property(x => x.CreateTime).HasColumnName(@"CreateTime").HasColumnType(@"datetime").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"current_timestamp()");
            modelBuilder.Entity<AuditEvent>().Property(x => x.DataType).HasColumnName(@"DataType").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(100).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<AuditEvent>().Property(x => x.DataKey).HasColumnName(@"DataKey").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(50).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<AuditEvent>().Property(x => x.Data).HasColumnName(@"Data").HasColumnType(@"longtext").ValueGeneratedOnAdd().HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<AuditEvent>().Property(x => x.AccountNo).HasColumnName(@"AccountNo").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(30).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<AuditEvent>().Property(x => x.HostAddress).HasColumnName(@"HostAddress").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(50).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<AuditEvent>().Property(x => x.ProcessStack).HasColumnName(@"ProcessStack").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(500).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<AuditEvent>().Property(x => x.Type).HasColumnName(@"Type").HasColumnType(@"int").ValueGeneratedOnAdd().HasPrecision(11, 0).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<AuditEvent>().HasKey(@"Id");
        }

        partial void CustomizeAuditEventMapping(ModelBuilder modelBuilder);

        #endregion

        #region Systemcode Mapping

        private void SystemcodeMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Systemcode>().ToTable(@"systemcode", @"pacs");
            modelBuilder.Entity<Systemcode>().Property(x => x.Category).HasColumnName(@"Category").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(11, 0);
            modelBuilder.Entity<Systemcode>().Property(x => x.Code).HasColumnName(@"Code").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<Systemcode>().Property(x => x.Display).HasColumnName(@"Display").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<Systemcode>().HasKey(@"Category", @"Code");
        }

        partial void CustomizeSystemcodeMapping(ModelBuilder modelBuilder);

        #endregion

        #region Pwdchangelog Mapping

        private void PwdchangelogMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Pwdchangelog>().ToTable(@"pwdchangelog", @"pacs");
            modelBuilder.Entity<Pwdchangelog>().Property(x => x.Id).HasColumnName(@"Id").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(11, 0);
            modelBuilder.Entity<Pwdchangelog>().Property(x => x.Account).HasColumnName(@"Account").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Pwdchangelog>().Property(x => x.Password).HasColumnName(@"Password").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            modelBuilder.Entity<Pwdchangelog>().Property(x => x.CreateTime).HasColumnName(@"CreateTime").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"current_timestamp()");
            modelBuilder.Entity<Pwdchangelog>().Property(x => x.CreatePractitionerId).HasColumnName(@"CreatePractitionerId").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(64).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<Pwdchangelog>().HasKey(@"Id");
        }

        partial void CustomizePwdchangelogMapping(ModelBuilder modelBuilder);

        #endregion

        #region UserProfile Mapping

        private void UserProfileMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<UserProfile>().ToTable(@"user_profile", @"pacs");
            modelBuilder.Entity<UserProfile>().Property(x => x.UserProfileNo).HasColumnName(@"UserProfileNo").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(8, 0);
            modelBuilder.Entity<UserProfile>().Property(x => x.UserID).HasColumnName(@"UserID").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(10).HasDefaultValueSql(@"''");
            modelBuilder.Entity<UserProfile>().Property(x => x.PassWord).HasColumnName(@"PassWord").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(32).HasDefaultValueSql(@"''");
            modelBuilder.Entity<UserProfile>().Property(x => x.UserName).HasColumnName(@"UserName").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(30).HasDefaultValueSql(@"''");
            modelBuilder.Entity<UserProfile>().Property(x => x.Level).HasColumnName(@"Level").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(1, 0).HasDefaultValueSql(@"0");
            modelBuilder.Entity<UserProfile>().Property(x => x.DepartNo).HasColumnName(@"DepartNo").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(4, 0).HasDefaultValueSql(@"0");
            modelBuilder.Entity<UserProfile>().Property(x => x.Status).HasColumnName(@"Status").HasColumnType(@"char").IsRequired().ValueGeneratedNever().HasMaxLength(1).HasDefaultValueSql(@"'N'");
            modelBuilder.Entity<UserProfile>().HasKey(@"UserProfileNo");
        }

        partial void CustomizeUserProfileMapping(ModelBuilder modelBuilder);

        #endregion

        #region DicomPicture Mapping

        private void DicomPictureMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DicomPicture>().ToTable(@"dicom_picture", @"pacs");
            modelBuilder.Entity<DicomPicture>().Property(x => x.Id).HasColumnName(@"Id").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(11, 0);
            modelBuilder.Entity<DicomPicture>().Property(x => x.StudyID).HasColumnName(@"StudyID").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(15).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<DicomPicture>().Property(x => x.Image).HasColumnName(@"image").HasColumnType(@"varchar").ValueGeneratedOnAdd().HasMaxLength(255).HasDefaultValueSql(@"NULL");
            modelBuilder.Entity<DicomPicture>().HasKey(@"Id");
        }

        partial void CustomizeDicomPictureMapping(ModelBuilder modelBuilder);

        #endregion

        private void RelationshipsMapping(ModelBuilder modelBuilder)
        {
        }

        partial void CustomizeMapping(ref ModelBuilder modelBuilder);

        public bool HasChanges()
        {
            return ChangeTracker.Entries().Any(e => e.State == Microsoft.EntityFrameworkCore.EntityState.Added || e.State == Microsoft.EntityFrameworkCore.EntityState.Modified || e.State == Microsoft.EntityFrameworkCore.EntityState.Deleted);
        }

        partial void OnCreated();
    }
}
