//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025/6/5 下午 02:31:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Api.Entities
{
    /// <summary>
    /// 影像圖檔
    /// </summary>
    public partial class DicomPicture {

        public DicomPicture()
        {
            OnCreated();
        }

        [Key]
        [Required()]
        public int Id { get; set; }

        [StringLength(15)]
        public string StudyID { get; set; }

        [StringLength(255)]
        public string Image { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
