//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025/6/5 下午 02:31:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Api.Entities
{
    /// <summary>
    /// 病歷報告資料
    /// </summary>
    public partial class ExamData {

        public ExamData()
        {
            OnCreated();
        }

        [Key]
        [Required()]
        public long ExamDataNo { get; set; }

        [StringLength(15)]
        public string StudyID { get; set; }

        public DateTime? ExamDateTime { get; set; }

        public string Memo1 { get; set; }

        /// <summary>
        /// 主述
        /// </summary>
        public string AdditionalPatientHistory { get; set; }

        public string English { get; set; }

        public string Recommand { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
