//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025/6/5 下午 02:31:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Api.Entities
{
    public partial class ImgPara {

        public ImgPara()
        {
            this.ImgRota = 0;
            this.ImgCount = 4;
            OnCreated();
        }

        [Key]
        [Required()]
        public byte Pid { get; set; }

        public long? ImgPosition { get; set; }

        public long? ImgWidth { get; set; }

        public long? ImgHeight { get; set; }

        public long? ImgRota { get; set; }

        public long? ImgCount { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
