//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025/6/5 下午 02:31:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Api.Entities
{
    public partial class ImportLog {

        public ImportLog()
        {
            OnCreated();
        }

        [Key]
        [Required()]
        public long Iid { get; set; }

        [StringLength(60)]
        public string Sname { get; set; }

        [StringLength(60)]
        public string Fname { get; set; }

        [StringLength(80)]
        public string Bname { get; set; }

        public DateTime? Idatetime { get; set; }

        public DateTime? Odatetime { get; set; }

        public DateTime? Sdatetime { get; set; }

        [StringLength(1)]
        public string Status { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
