//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025/6/5 下午 02:31:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Api.Entities
{
    /// <summary>
    /// 病患
    /// </summary>
    public partial class PatientMain {

        public PatientMain()
        {
            OnCreated();
        }

        [Key]
        [Required()]
        public int PatientMainNo { get; set; }

        [StringLength(20)]
        [Required()]
        public string PatientID { get; set; }

        [StringLength(20)]
        [Required()]
        public string PatientName { get; set; }

        public DateTime? PatientBirthDate { get; set; }

        [StringLength(10)]
        [Required()]
        public string PatientSex { get; set; }

        [StringLength(10)]
        public string OtherPatientID { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
