//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025/6/5 下午 02:31:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Api.Entities
{
    /// <summary>
    /// 病患檢查明細檔
    /// </summary>
    public partial class PatientDetail {

        public PatientDetail()
        {
            this.SeriesNumber = 0;
            this.Status = @"N";
            OnCreated();
        }

        [Key]
        [Required()]
        public long DetailNo { get; set; }

        [StringLength(15)]
        [Required()]
        public string StudyID { get; set; }

        [StringLength(20)]
        [Required()]
        public string PatientID { get; set; }

        public int? SeriesNumber { get; set; }

        public DateTime? StudyDate { get; set; }

        public DateTime? ContentDate { get; set; }

        public TimeSpan? StudyTime { get; set; }

        public TimeSpan? ContentTime { get; set; }

        [StringLength(10)]
        public string Modality { get; set; }

        [StringLength(20)]
        public string OperatorName { get; set; }

        [StringLength(50)]
        public string Manufacturer { get; set; }

        [StringLength(100)]
        public string BodyPartExamined { get; set; }

        [StringLength(50)]
        public string ProtocolName { get; set; }

        [StringLength(30)]
        public string AccessionNumber { get; set; }

        public sbyte? InstanceNumber { get; set; }

        [StringLength(50)]
        public string Image { get; set; }

        [StringLength(1)]
        [Required()]
        public string Status { get; set; }

        [StringLength(100)]
        public string AdditionalPatientHistory { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
