//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025/6/5 下午 02:31:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Api.Entities
{
    /// <summary>
    /// 密碼變更log
    /// </summary>
    public partial class Pwdchangelog {

        public Pwdchangelog()
        {
            OnCreated();
        }

        /// <summary>
        /// 序號
        /// </summary>
        [Key]
        [Required()]
        public int Id { get; set; }

        /// <summary>
        /// 帳號
        /// </summary>
        [StringLength(50)]
        [Required()]
        public string Account { get; set; }

        /// <summary>
        /// 密碼
        /// </summary>
        [StringLength(64)]
        [Required()]
        public string Password { get; set; }

        /// <summary>
        /// 建立時間
        /// </summary>
        public DateTime? CreateTime { get; set; }

        /// <summary>
        /// 建立人員ID
        /// </summary>
        [StringLength(64)]
        public string CreatePractitionerId { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
