//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025/6/5 下午 02:31:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Api.Entities
{
    public partial class ReportCodeDesc {

        public ReportCodeDesc()
        {
            OnCreated();
        }

        [Key]
        [Required()]
        public int ReportCodeDescNo { get; set; }

        [StringLength(64)]
        [Required()]
        public string ReportCode { get; set; }

        public string ReportDesc { get; set; }

        [StringLength(255)]
        [Required()]
        public string UserID { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
