//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025/6/5 下午 02:31:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Api.Entities
{
    /// <summary>
    /// 基本資料代碼表
    /// </summary>
    public partial class Systemcode {

        public Systemcode()
        {
            OnCreated();
        }

        /// <summary>
        /// 類型
        /// </summary>
        [Key]
        [Required()]
        public int Category { get; set; }

        /// <summary>
        /// 代碼
        /// </summary>
        [Key]
        [StringLength(20)]
        [Required()]
        public string Code { get; set; }

        /// <summary>
        /// 顯示文字
        /// </summary>
        [StringLength(100)]
        [Required()]
        public string Display { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          Systemcode toCompare = obj as Systemcode;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Category, toCompare.Category))
            return false;
          if (!Object.Equals(this.Code, toCompare.Code))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Category.GetHashCode();
          hashCode = (hashCode * 7) + Code.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
