//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025/6/5 下午 02:31:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace Api.Entities
{
    public partial class UserProfile {

        public UserProfile()
        {
            this.UserID = @"";
            this.PassWord = @"";
            this.UserName = @"";
            this.Level = 0;
            this.DepartNo = 0;
            this.Status = @"N";
            OnCreated();
        }

        [Key]
        [Required()]
        public int UserProfileNo { get; set; }

        [StringLength(10)]
        [Required()]
        public string UserID { get; set; }

        [StringLength(32)]
        [Required()]
        public string PassWord { get; set; }

        [StringLength(30)]
        [Required()]
        public string UserName { get; set; }

        [Required()]
        public int Level { get; set; }

        [Required()]
        public int DepartNo { get; set; }

        [StringLength(1)]
        [Required()]
        public string Status { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
